#!/usr/bin/env python3
"""D11: Fixed-point SiLU LUT reference (Python == RTL).

Frozen: input signed INT8, index = x + 128 into 256-entry LUT.
Output signed INT8 = round(silu(x)) with x treated as float from int8 value.
For large |x|, silu saturates; LUT built once offline.
"""

from __future__ import annotations

import math

SILU_LUT_SIZE = 256
SILU_LUT_MIN = -128
SILU_LUT_MAX = 127


def silu_float(x: float) -> float:
    if x <= -20.0:
        return 0.0
    return x / (1.0 + math.exp(-x))


def build_silu_lut() -> list[int]:
    lut: list[int] = []
    for i in range(SILU_LUT_SIZE):
        x = SILU_LUT_MIN + i
        v = silu_float(float(x))
        q = int(round(v))
        if q > 127:
            q = 127
        if q < -127:
            q = -127
        lut.append(q)
    return lut


SILU_LUT = build_silu_lut()


def silu_int8(x: int) -> int:
    xi = int(x)
    if xi < SILU_LUT_MIN:
        xi = SILU_LUT_MIN
    if xi > SILU_LUT_MAX:
        xi = SILU_LUT_MAX
    return SILU_LUT[xi - SILU_LUT_MIN]


def emit_sverilog_lut(path: str) -> None:
    lines = [
        "// Auto-generated by scripts/silu_fixed_ref.py — paste into int8_silu_lut initial block",
    ]
    for i, v in enumerate(SILU_LUT):
        lines.append(f"        lut[{i}] = 8'sd{v};")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    import sys

    out = sys.argv[1] if len(sys.argv) > 1 else "silu_lut_params.svh"
    emit_sverilog_lut(out)
    print(f"Wrote {SILU_LUT_SIZE} entries to {out}")
