#!/usr/bin/env python3
"""D9: Shared fixed-point causal softmax reference (Python == RTL).

Frozen format:
  SCALE_MULT=1, SCALE_SHIFT=2          # /4 == /sqrt(16)
  Score domain after scale: INT32
  Causal mask: set to MASK_VAL = -2^30
  EXP_LUT: maps x in [-32,0] (clamped) to UQ0.15  (0..32767)
  RECIP: 32-bit / sum_e with reciprocal table on sum_e in [1..65535]
  Output: UQ1.15 (0..32768), masked positions = 0
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np

SCALE_MULT = 1
SCALE_SHIFT = 2
MASK_VAL = -(1 << 30)
EXP_MIN = -32
EXP_MAX = 0
EXP_LUT_SIZE = EXP_MAX - EXP_MIN + 1  # 33
P_FRAC = 15
ONE_Q15 = 1 << P_FRAC


def build_exp_lut() -> list[int]:
    """exp(x) for x in [-32..0], as UQ0.15, exp(0)=32767."""
    lut: list[int] = []
    for i in range(EXP_LUT_SIZE):
        x = EXP_MIN + i
        # Use float only to build table once; RTL embeds same constants.
        v = math.exp(x)
        q = int(round(v * (ONE_Q15 - 1)))
        if q < 0:
            q = 0
        if q > ONE_Q15 - 1:
            q = ONE_Q15 - 1
        lut.append(q)
    lut[EXP_LUT_SIZE - 1] = ONE_Q15 - 1  # exp(0)
    return lut


EXP_LUT = build_exp_lut()


def recip_u16(denom: int) -> int:
    """Return floor((1<<31) / denom) for denom>=1, as UQ16.15-ish helper."""
    if denom <= 0:
        return 0
    return (1 << 31) // denom


def fixed_softmax_row(scores: list[int], row: int) -> list[int]:
    seq = len(scores)
    scaled = [(int(s) * SCALE_MULT) >> SCALE_SHIFT for s in scores]
    for j in range(seq):
        if j > row:
            scaled[j] = MASK_VAL

    # max over non-masked
    mx = None
    for j in range(seq):
        if j <= row:
            mx = scaled[j] if mx is None else max(mx, scaled[j])
    if mx is None:
        return [0] * seq

    exps = [0] * seq
    sum_e = 0
    for j in range(seq):
        if j > row:
            exps[j] = 0
            continue
        x = scaled[j] - mx
        if x < EXP_MIN:
            x = EXP_MIN
        if x > EXP_MAX:
            x = EXP_MAX
        e = EXP_LUT[x - EXP_MIN]
        exps[j] = e
        sum_e += e

    if sum_e <= 0:
        return [0] * seq

    inv = recip_u16(sum_e)  # (1<<31)/sum
    probs = [0] * seq
    for j in range(seq):
        if j > row:
            probs[j] = 0
        else:
            # (e * inv) >> (31-15) = (e * inv) >> 16 → UQ1.15
            probs[j] = (exps[j] * inv) >> 16
    return probs


def fixed_softmax_matrix(score: np.ndarray) -> np.ndarray:
    seq = score.shape[0]
    out = np.zeros((seq, seq), dtype=np.int32)
    for i in range(seq):
        out[i, :] = fixed_softmax_row([int(v) for v in score[i, :]], i)
    return out


def emit_rtl_lut_header(path: Path) -> None:
    lines = [
        "// Auto-generated by scripts/softmax_fixed_ref.py — do not hand-edit",
        f"localparam int SOFT_SCALE_MULT = {SCALE_MULT};",
        f"localparam int SOFT_SCALE_SHIFT = {SCALE_SHIFT};",
        f"localparam int SOFT_MASK_VAL = {MASK_VAL};",
        f"localparam int SOFT_EXP_MIN = {EXP_MIN};",
        f"localparam int SOFT_EXP_MAX = {EXP_MAX};",
        f"localparam int SOFT_P_FRAC = {P_FRAC};",
        "localparam logic [14:0] SOFT_EXP_LUT [0:32] = '{",
    ]
    lines.append("    " + ", ".join(f"15'd{v}" for v in EXP_LUT))
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    emit_rtl_lut_header(root / "requantize_int8_rtl.srcs" / "sources_1" / "new" / "softmax_lut_params.svh")
    print("EXP_LUT[0]=", EXP_LUT[0], "EXP_LUT[-1]=", EXP_LUT[-1])
    s = np.array([[10, 20, 30, 40], [1, 2, 3, 4], [0, 0, 0, 0], [-5, -4, -3, -2]], dtype=np.int32)
    print(fixed_softmax_matrix(s))
